# Generated by Django 4.1.1 on 2022-10-08 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedb_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedb',
            name='cast1',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='cast2',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='cast3',
        ),
        migrations.AddField(
            model_name='moviedb',
            name='cast',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
