# Generated by Django 4.1.1 on 2022-10-08 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_moviedb_cast1_remove_moviedb_cast2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedb',
            name='cast',
        ),
        migrations.AddField(
            model_name='moviedb',
            name='cast1',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedb',
            name='cast2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedb',
            name='cast3',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
